sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/google-traffic-screen:latest .
      - docker images
      - docker push $DOCKER_USERNAME/google-traffic-screen:latest
      - docker tag $DOCKER_USERNAME/google-traffic-screen:latest $DOCKER_USERNAME/google-traffic-screen:r2
      - docker push $DOCKER_USERNAME/google-traffic-screen:r2