sudo: true
dist: trusty
language: minimal
if: branch = master
services:
  - docker

env:
  global:
    - DOCKER_USERNAME=alatas
    - AUTHOR=alatas
    - REPO_NAME=google-traffic-screen

before_script:
  - export TAG=$(echo $TRAVIS_COMMIT_MESSAGE | egrep -o 'r[0-9]+')

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/$REPO_NAME:latest .
  - docker images
  - docker push $DOCKER_USERNAME/$REPO_NAME:latest
  - docker tag $DOCKER_USERNAME/$REPO_NAME:latest $DOCKER_USERNAME/$REPO_NAME:$TAG
  - docker push $DOCKER_USERNAME/$REPO_NAME:$TAG

before_deploy:
  - git tag -f "$TAG" -m "$TRAVIS_COMMIT_MESSAGE"
  - git tag
  - export DEPLOY_DOCKER=$TRAVIS_BUILD_DIR/../deploy_docker
  - export DEPLOY_NODOCKER=$TRAVIS_BUILD_DIR/../deploy_nodocker
  - mkdir -p $DEPLOY_DOCKER
  - mkdir -p $DEPLOY_NODOCKER
  - mkdir -p $DEPLOY_DOCKER/www
  - mkdir -p $DEPLOY_NODOCKER/www
  - cp -f $TRAVIS_BUILD_DIR/*.py $TRAVIS_BUILD_DIR/*.yml $DEPLOY_DOCKER
  - sed -i 's/latest/$TAG/g' $DEPLOY_DOCKER/docker-compose.yml 
  - cp -f $TRAVIS_BUILD_DIR/www/index.html $DEPLOY_DOCKER/www
  - cp -f $TRAVIS_BUILD_DIR/*.py $TRAVIS_BUILD_DIR/settings.yml $TRAVIS_BUILD_DIR/locations.yml $DEPLOY_NODOCKER
  - cp -f $TRAVIS_BUILD_DIR/www/* $DEPLOY_NODOCKER/www
  - rm -f "$DEPLOY_DOCKER/../$REPO_NAME-$TAG-docker.zip" && cd $DEPLOY_DOCKER/ && zip -r -J "$DEPLOY_DOCKER/../$REPO_NAME-$TAG-docker.zip" *
  - rm -f "$DEPLOY_NODOCKER/../$REPO_NAME-$TAG.zip" && cd $DEPLOY_NODOCKER/ && zip -r -J "$DEPLOY_NODOCKER/../$REPO_NAME-$TAG.zip" *
  - cd $TRAVIS_BUILD_DIR/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - "$DEPLOY_DOCKER/../$REPO_NAME-$TAG-docker.zip"
    - "$DEPLOY_NODOCKER/../$REPO_NAME-$TAG.zip"
  overwrite: true
  skip_cleanup: true
  on:
    repo: $AUTHOR/$REPO_NAME
    all_branches: true